In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import re
import xml.etree.ElementTree as ET
from functools import reduce
import openpyxl
from scipy.optimize import minimize_scalar
import numpy as np
import glob

pd.set_option('display.max_columns', None)

# Interest rate

In [2]:
INTEREST_URL = "https://index.minfin.com.ua/en/banks/nbu/refinance/"

In [ ]:
def scrape_nbu_rate_monthly_avg(start_month="2010-01", end_month="2025-12"):
    r = requests.get(INTEREST_URL, timeout=30)
    r.raise_for_status()

    soup = BeautifulSoup(r.text, "html.parser")
    text = soup.get_text("\n", strip=True)

    pattern = re.compile(
        r"from\s+(\d{2}\.\d{2}\.\d{4})"
        r"(?:\s+to\s+(\d{2}\.\d{2}\.\d{4}))?"
        r"\s+(\d+,\d{2})"
    )

    matches = pattern.findall(text)
    if not matches:
        raise ValueError("Could not parse the rate table. The page structure may have changed.")

    df = pd.DataFrame(matches, columns=["date_from", "date_to", "rate_raw"])

    df["date_from"] = pd.to_datetime(df["date_from"], format="%d.%m.%Y")
    df["date_to"] = pd.to_datetime(
        df["date_to"].replace("", pd.NA),
        format="%d.%m.%Y",
        errors="coerce"
    )
    df["rate"] = df["rate_raw"].str.replace(",", ".", regex=False).astype(float)

    df["date_to"] = df["date_to"].fillna(pd.Timestamp("2100-12-31"))

    df = df.sort_values("date_from").reset_index(drop=True)

    months = pd.period_range(start=start_month, end=end_month, freq="M")
    result = []

    for month in months:
        month_start = month.start_time.normalize()
        month_end = month.end_time.normalize()

        weighted_sum = 0.0
        total_days = 0

        for _, row in df.iterrows():
            overlap_start = max(month_start, row["date_from"])
            overlap_end = min(month_end, row["date_to"])

            if overlap_start <= overlap_end:
                days = (overlap_end - overlap_start).days + 1
                weighted_sum += row["rate"] * days
                total_days += days

        avg_rate = weighted_sum / total_days if total_days > 0 else pd.NA

        result.append({
            "month": str(month),
            "value": avg_rate
        })

    out = pd.DataFrame(result)
    return out

In [4]:
monthly_avg_rates = scrape_nbu_rate_monthly_avg()
monthly_avg_rates["value"] = monthly_avg_rates["value"].round(4)

monthly_avg_rates.tail()

       month  value
187  2025-08   15.5
188  2025-09   15.5
189  2025-10   15.5
190  2025-11   15.5
191  2025-12   15.5

In [5]:
monthly_avg_rates["month"] = pd.to_datetime(monthly_avg_rates["month"])
monthly_avg_rates["year-quarter"] = monthly_avg_rates["month"].dt.to_period("Q").astype(str)

quarterly_rates = (
    monthly_avg_rates.groupby("year-quarter", as_index=False)["value"]
    .mean()
    .rename(columns={"value": "interest_rate_avg_q"})
)

quarterly_rates

   year-quarter  interest_rate_avg_q
0        2010Q1            10.250000
1        2010Q2            10.058333
2        2010Q3             8.147833
3        2010Q4             7.750000
4        2011Q1             7.750000
..          ...                  ...
59       2024Q4            13.102167
60       2025Q1            14.521533
61       2025Q2            15.500000
62       2025Q3            15.500000
63       2025Q4            15.500000

[64 rows x 2 columns]

# Exchange rate

In [6]:
def fetch_nbu_fx_quarterly_avg(valcode="USD", start="2010-01-01", end="2024-12-31"):
    url = "https://bank.gov.ua/NBU_Exchange/exchange_site"

    params = {
        "start": pd.to_datetime(start).strftime("%Y%m%d"),
        "end": pd.to_datetime(end).strftime("%Y%m%d"),
        "valcode": valcode,
        "json": "",
        "sort": "exchangedate",
        "order": "asc",
    }

    r = requests.get(url, params=params, timeout=60)
    r.raise_for_status()
    data = r.json()

    df = pd.DataFrame(data)
    if df.empty:
        return df

    df["dt"] = pd.to_datetime(df["exchangedate"], format="%d.%m.%Y")
    df["year-quarter"] = df["dt"].dt.to_period("Q").astype(str)

    out = (
        df.groupby("year-quarter", as_index=False)["rate"]
        .mean()
        .rename(columns={"rate": f"{valcode.lower()}_avg_q"})
    )

    return out

In [7]:
usd_q = fetch_nbu_fx_quarterly_avg(
    valcode="USD",
    start="2010-01-01",
    end="2024-12-31"
)

eur_q = fetch_nbu_fx_quarterly_avg(
    valcode="EUR",
    start="2010-01-01",
    end="2024-12-31"
)

exchange_rates = pd.merge(usd_q, eur_q, on="year-quarter", how="outer").sort_values("year-quarter").reset_index(drop=True)
exchange_rates.head()

  year-quarter   usd_avg_q    eur_avg_q
0       2010Q1  798.770556  1107.207786
1       2010Q2  792.243077  1010.101635
2       2010Q3  790.062717  1017.562051
3       2010Q4  793.136848  1078.512101
4       2011Q1  794.495222  1084.949968

# CPI

In [8]:
CPI_URL = 'https://stat.gov.ua/sdmx/workspaces/default:integration/registry/sdmx/3.0/data/dataflow/SSSU/DF_PRICE_CHANGE_CONSUMER_GOODS_SERVICE/27.0.0/INDEX_CONSUMPRICE.DEC2010.UA00000000000000000.0.M'

def fetch_sdmx_series1525(url: str) -> pd.DataFrame:
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/122.0.0.0 Safari/537.36"
        ),
        "Accept": "application/xml, text/xml, */*",
        "Referer": "https://stat.gov.ua/uk/development-api/sdmx-api-v3",
    }

    response = requests.get(url, headers=headers, timeout=60)
    response.raise_for_status()

    root = ET.fromstring(response.content)

    series = root.find(".//Series")
    if series is None:
        raise ValueError("No <Series> found in response")

    scale = pd.to_numeric(series.attrib.get("SCALE"), errors="coerce")

    rows = []
    for obs in series.findall("./Obs"):
        rows.append({
            "year_quarter": obs.attrib.get("TIME_PERIOD"),
            "value": pd.to_numeric(obs.attrib.get("OBS_VALUE"), errors="coerce"),
            "scale": scale
        })

    df = pd.DataFrame(rows)

    if df.empty:
        raise ValueError("Series found, but no observations were extracted")

    return df

In [9]:
cpi_base_2010 = fetch_sdmx_series1525(CPI_URL)[["year_quarter", "value"]]

cpi_base_2010 = cpi_base_2010.drop(columns=["scale"], errors="ignore")

cpi_base_2010["date"] = pd.PeriodIndex(
    cpi_base_2010["year_quarter"].str.replace("-M", "-", regex=False),
    freq="M"
)

cpi_base_2010 = (
    cpi_base_2010.groupby(cpi_base_2010["date"].dt.asfreq("Q"))["value"]
    .mean()
    .reset_index()
)

cpi_base_2010["year_quarter"] = cpi_base_2010["date"].astype(str)
cpi_base_2010 = cpi_base_2010.drop(columns="date")
cpi_base_2010 = cpi_base_2010.rename(columns={"value": "cpi_base_2010"})
cpi_base_2010 = cpi_base_2010[
    (cpi_base_2010["year_quarter"] < "2025Q1") &
    (cpi_base_2010["year_quarter"] >= "2010Q1")
].reset_index(drop=True)
cpi_base_2010 = cpi_base_2010[["year_quarter", "cpi_base_2010"]]

cpi_base_2010

   year_quarter  cpi_base_2010
0        2010Q1      94.766667
1        2010Q2      95.166667
2        2010Q3      96.166667
3        2010Q4      99.366667
4        2011Q1     102.066667
5        2011Q2     105.366667
6        2011Q3     104.300000
7        2011Q4     104.400000
8        2012Q1     105.033333
9        2012Q2     105.000000
10       2012Q3     104.266667
11       2012Q4     104.200000
12       2013Q1     104.533333
13       2013Q2     104.566667
14       2013Q3     103.966667
15       2013Q4     104.433333
16       2014Q1     106.266667
17       2014Q2     114.800000
18       2014Q3     119.233333
19       2014Q4     127.600000
20       2015Q1     144.900000
21       2015Q2     182.466667
22       2015Q3     182.800000
23       2015Q4     185.600000
24       2016Q1     189.500000
25       2016Q2     197.100000
26       2016Q3     197.566667
27       2016Q4     208.400000
28       2017Q1     215.900000
29       2017Q2     224.266667
30       2017Q3     229.433333
31       2017Q4     237.400000
32       2018Q1     245.666667
33       2018Q2     250.200000
34       2018Q3     249.966667
35       2018Q4     260.500000
36       2019Q1     267.433333
37       2019Q2     273.000000
38       2019Q3     271.200000
39       2019Q4     274.066667
40       2020Q1     274.500000
41       2020Q2     278.633333
42       2020Q3     277.700000
43       2020Q4     284.533333
44       2021Q1     294.800000
45       2021Q2     304.000000
46       2021Q3     306.833333
47       2021Q4     314.166667
48       2022Q1     328.666667
49       2022Q2     360.700000
50       2022Q3     379.033333
51       2022Q4     397.600000
52       2023Q1     407.500000
53       2023Q2     415.800000
54       2023Q3     413.000000
55       2023Q4     418.066667
56       2024Q1     423.966667
57       2024Q2     431.466667
58       2024Q3     442.600000
59       2024Q4     463.900000

# Final

In [10]:
rates = exchange_rates.merge(quarterly_rates, on="year-quarter", how="outer").sort_values("year-quarter").reset_index(drop=True) \
    .merge(cpi_base_2010, left_on="year-quarter", right_on="year_quarter", how="outer") \
    .drop(columns=["year-quarter"], errors="ignore")
rates = rates[rates['year_quarter'] < '2025Q1']

rates = rates[["year_quarter", "usd_avg_q", "eur_avg_q", "interest_rate_avg_q", "cpi_base_2010"]]
rates

   year_quarter    usd_avg_q    eur_avg_q  interest_rate_avg_q  cpi_base_2010
0        2010Q1   798.770556  1107.207786            10.250000      94.766667
1        2010Q2   792.243077  1010.101635            10.058333      95.166667
2        2010Q3   790.062717  1017.562051             8.147833      96.166667
3        2010Q4   793.136848  1078.512101             7.750000      99.366667
4        2011Q1   794.495222  1084.949968             7.750000     102.066667
5        2011Q2   797.097253  1147.687592             7.750000     105.366667
6        2011Q3   797.170652  1127.782843             7.750000     104.300000
7        2011Q4   798.276957  1076.499504             7.750000     104.400000
8        2012Q1   798.815495  1045.743513             7.725800     105.033333
9        2012Q2   799.000769  1026.279065             7.500000     105.000000
10       2012Q3   799.295652   998.611321             7.500000     104.266667
11       2012Q4   799.300000  1037.248140             7.500000     104.200000
12       2013Q1   799.300000  1054.897497             7.500000     104.533333
13       2013Q2   799.300000  1043.560814             7.383333     104.566667
14       2013Q3   799.300000  1058.315778             6.731167     103.966667
15       2013Q4   799.300000  1087.550178             6.500000     104.433333
16       2014Q1   886.267333  1214.770717             6.500000     106.266667
17       2014Q2  1169.617545  1604.270648             9.033333     114.800000
18       2014Q3  1257.715267  1667.308975            11.983867     119.233333
19       2014Q4  1443.359628  1802.585884            13.300000     127.600000
20       2015Q1  2111.566569  2378.934437            20.500600     144.900000
21       2015Q2  2161.145137  2387.087541            30.000000     182.466667
22       2015Q3  2172.189165  2413.254957            28.537633     182.800000
23       2015Q4  2284.912234  2501.613379            22.000000     185.600000
24       2016Q1  2565.373637  2827.640437            22.000000     189.500000
25       2016Q2  2526.225953  2855.367930            19.196233     197.100000
26       2016Q3  2537.601263  2834.633482            15.717733     197.566667
27       2016Q4  2588.960708  2795.796032            14.290333     208.400000
28       2017Q1  2706.105549  2880.885859            14.000000     215.900000
29       2017Q2  2646.269276  2906.404804            12.945500     224.266667
30       2017Q3  2590.217825  3037.772777            12.500000     229.433333
31       2017Q4  2696.167690  3176.426225            13.403233     237.400000
32       2018Q1  2732.034352  3356.329850            15.919333     245.666667
33       2018Q2  2617.841245  3126.778459            17.000000     250.200000
34       2018Q3  2734.899763  3181.313709            17.568833     249.966667
35       2018Q4  2795.018586  3191.373841            18.000000     260.500000
36       2019Q1  2730.581127  3102.926020            18.000000     267.433333
37       2019Q2  2656.145557  2983.274667            17.638900     273.000000
38       2019Q3  2526.130891  2810.094311            16.957867     271.200000
39       2019Q4  2324.103367  2571.706641            15.349467     274.066667
40       2020Q1    25.052530    27.615378            11.602167     274.500000
41       2020Q2    26.914331    29.602818             8.088867     278.633333
42       2020Q3    27.599603    32.242895             6.000000     277.700000
43       2020Q4    28.267820    33.696490             6.000000     284.533333
44       2021Q1    27.969397    33.756891             6.145167     294.800000
45       2021Q2    27.591041    33.233168             7.333333     304.000000
46       2021Q3    26.911034    31.738760             7.998400     306.833333
47       2021Q4    26.680642    30.516714             8.618267     314.166667
48       2022Q1    28.554488    32.278843             9.784933     328.666667
49       2022Q2    29.254900    31.198413            14.666667     360.700000
50       2022Q3    34.978665    35.184347            25.000000     379.033333
51       2022Q4    36.568600    37.252234            25.000000     397.600000
52       2023Q1    36.568600    39.223298            25.000000     407.500000
53       2023Q2    36.568600    39.820536            25.000000     415.800000
54       2023Q3    36.568600    39.836423            22.515400     413.000000
55       2023Q4    36.594150    39.362768            16.935467     418.066667
56       2024Q1    38.172709    41.466826            14.908600     423.966667
57       2024Q2    39.847841    42.907933            13.683333     431.466667
58       2024Q3    41.141162    45.168892            13.000000     442.600000
59       2024Q4    41.449309    44.263757            13.102167     463.900000

In [11]:
rates["year_quarter"] = pd.PeriodIndex(rates["year_quarter"], freq="Q")

mask = rates["year_quarter"] < pd.Period("2020Q1", freq="Q")

rates.loc[mask, ["usd_avg_q", "eur_avg_q"]] = (
    rates.loc[mask, ["usd_avg_q", "eur_avg_q"]] / 100
)

In [13]:
rates.to_csv("data/rates_2010_2024.csv", index=False)